#
# $Id: Makefile 12150 2009-08-17 17:32:21Z vszakats $
#

ROOT := ../../../

C_SOURCES := \
   sxcompr.c \
   sxcrypt.c \
   sxdate.c \
   sxsem.c \
   sxfname.c \
   sxtable.c \
   sxord.c \
   sxutil.c \
   sxredir.c \

PRG_SOURCES := \
   sxcompat.prg \
   sxini.prg \
   sxtrig.prg \

LIBNAME := hbsix

include $(TOP)$(ROOT)config/lib.mk
