//NOTEST
//
// $Id: lnlenli1.prg 11201 2009-06-03 10:26:40Z vszakats $
//

// ; Pushing Harbour preprocessor to the line length limit.
// ; Donated to the public domain by
//   Viktor Szakats (harbour.01 syenar.hu)

FUNCTION Main()

     LongLine1()

     RETURN 0

FUNCTION LongLine1()
     RETURN {;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9}}

