#
# $Id: Makefile 13836 2010-02-10 11:34:42Z druzus $
#

ROOT := ../../../

include $(TOP)$(ROOT)config/global.mk

vpath %.c ../

C_SOURCES := \
   maindllh.c \

LIBNAME := hbmaindllh

include $(TOP)$(ROOT)config/lib.mk
