#
# $Id: Makefile 12150 2009-08-17 17:32:21Z vszakats $
#

ROOT := ../../

C_SOURCES := \
   dbgentry.c \

PRG_SOURCES := \
   dbgmenu.prg \
   dbghelp.prg \
   dbgtinp.prg \
   dbgtmenu.prg \
   dbgtmitm.prg \
   dbgtwin.prg \
   debugger.prg \
   dbgtarr.prg \
   dbgthsh.prg \
   dbgtobj.prg \
   tbrwtext.prg \
   dbgwa.prg \
   dbgbrwsr.prg \

LIBNAME := hbdebug

include $(TOP)$(ROOT)config/lib.mk
