#
# $Id: Makefile 12370 2009-08-30 08:29:20Z druzus $
#

ROOT := ../../

C_SOURCES := \

C_MAIN := harbour.c

LIBS := \
   hbcplr \
   hbpp \
   hbnortl \
   hbcommon \

include $(TOP)$(ROOT)config/bin.mk
