#
# $Id: Makefile 12150 2009-08-17 17:32:21Z vszakats $
#

ROOT := ../../../../

PRG_SOURCES := \
   arrayrdd.prg \
   logrdd.prg \
   hscdx.prg \
   rlcdx.prg \
   dbtcdx.prg \
   fptcdx.prg \
   smtcdx.prg \
   vfpcdx.prg \

LIBNAME := hbuddall

include $(TOP)$(ROOT)config/lib.mk
