#
# $Id: Makefile 13836 2010-02-10 11:34:42Z druzus $
#

ROOT := ../../../

include $(TOP)$(ROOT)config/global.mk

C_SOURCES := \
   dllpcode.c \
   dllext.c   \

LIBNAME := hbmaindllp

include $(TOP)$(ROOT)config/lib.mk
